# Generated by Django 3.2.10 on 2023-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
