# Generated by Django 3.2.10 on 2023-10-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_expense_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
    ]
