# Generated by Django 3.2.10 on 2023-11-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
